Script started on 2023-02-09 11:43:53-08:00
]0;marcosta@WWWSTU-P01:~/hw1marcosta@WWWSTU-P01:~/hw1> sudo ./initials.c[5P./initials.c[K[K
MMMMMMMMMMMMM
            M
         MM  
      MMM    
     M       
      MMM    
         MM  
            M
MMMMMMMMMMMMM
    CCCCCCCC 
  C          
 C           
C            
C            
 C           
  C          
    CCCCCCCC 
]0;marcosta@WWWSTU-P01:~/hw1marcosta@WWWSTU-P01:~/hw1> exit

Script done on 2023-02-09 11:44:05-08:00
