Script started on 2023-03-03 11:59:13-08:00
]0;marcosta@WWWSTU-P01:~/hw3marcosta@WWWSTU-P01:~/hw3> ./blackjha[K[Kack
************************************
** Welcome to CENG 231 BlackJack! **
************************************
Your first card is: 5
Do you want another card?
Type 1 for Yes, 0 for No: 1
Your next card is: 2
Your combined value is: 7
Do you want another card?
Type 1 for Yes, 0 for No: 1
Your next card is: 7
Your combined value is: 14
Do you want another card?
Type 1 for Yes, 0 for No: 1
Your next card is: 13
Your combined value is: 24
Sorry. You lose!
]0;marcosta@WWWSTU-P01:~/hw3marcosta@WWWSTU-P01:~/hw3> exit
exit

Script done on 2023-03-03 11:59:23-08:00
