Script started on 2023-05-01 09:46:47-07:00
.]0;marcosta@WWWSTU-P01:~/hw7marcosta@WWWSTU-P01:~/hw7> ./PhotoLab
wilson.ppm was read successfully!
aging.ppm was saved successfully. 
aging.jpg was stored for viewing. 
Aging tested!

wilson.ppm was read successfully!
bw.ppm was saved successfully. 
bw.jpg was stored for viewing. 
Black and White tested!

wilson.ppm was read successfully!
negative.ppm was saved successfully. 
negative.jpg was stored for viewing. 
Negative tested!

wilson.ppm was read successfully!
vflip.ppm was saved successfully. 
vflip.jpg was stored for viewing. 
VFlip tested!

wilson.ppm was read successfully!
hmirror.ppm was saved successfully. 
hmirror.jpg was stored for viewing. 
HMirror tested!

wilson.ppm was read successfully!
sharpen.ppm was saved successfully. 
sharpen.jpg was stored for viewing. 
Sharpen tested!

wilson.ppm was read successfully!
xRB.ppm was saved successfully. 
xRB.jpg was stored for viewing. 
ExRB tested!

wilson.ppm was read successfully!
crop.ppm was saved successfully. 
crop.jpg was stored for viewing. 
Crop tested!

AutoTest finished.
]0;marcosta@WWWSTU-P01:~/hw7marcosta@WWWSTU-P01:~/hw7> valgrind --leak-check=full PhotoLab[C/PhotoLab[1PPhotoLab.PhotoLab/PhotoLab
==928989== Memcheck, a memory error detector
==928989== Copyright (C) 2002-2022, and GNU GPL'd, by Julian Seward et al.
==928989== Using Valgrind-3.19.0 and LibVEX; rerun with -h for copyright info
==928989== Command: ./PhotoLab
==928989== 
wilson.ppm was read successfully!
aging.ppm was saved successfully. 
aging.jpg was stored for viewing. 
Aging tested!

wilson.ppm was read successfully!
bw.ppm was saved successfully. 
bw.jpg was stored for viewing. 
Black and White tested!

wilson.ppm was read successfully!
negative.ppm was saved successfully. 
negative.jpg was stored for viewing. 
Negative tested!

wilson.ppm was read successfully!
vflip.ppm was saved successfully. 
vflip.jpg was stored for viewing. 
VFlip tested!

wilson.ppm was read successfully!
hmirror.ppm was saved successfully. 
hmirror.jpg was stored for viewing. 
HMirror tested!

wilson.ppm was read successfully!
sharpen.ppm was saved successfully. 
sharpen.jpg was stored for viewing. 
Sharpen tested!

wilson.ppm was read successfully!
xRB.ppm was saved successfully. 
xRB.jpg was stored for viewing. 
ExRB tested!

wilson.ppm was read successfully!
crop.ppm was saved successfully. 
crop.jpg was stored for viewing. 
Crop tested!

AutoTest finished.
==928989== 
==928989== HEAP SUMMARY:
==928989==     in use at exit: 0 bytes in 0 blocks
==928989==   total heap usage: 69 allocs, 69 frees, 3,491,506 bytes allocated
==928989== 
==928989== All heap blocks were freed -- no leaks are possible
==928989== 
==928989== For lists of detected and suppressed errors, rerun with: -s
==928989== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
]0;marcosta@WWWSTU-P01:~/hw7marcosta@WWWSTU-P01:~/hw7> exit
exit

Script done on 2023-05-01 09:47:50-07:00
